### ISSUE TITLE
Switching to a visible REPL does not work with pop-to-buffer

### ISSUE THREAD

**Issue by Wilfred** [tomterl/repl-toggle#10]
Given the following configuration:

```emacs-lisp
  (setq rtog/mode-repl-alist '((emacs-lisp-mode . ielm)))
  (setq rtog/goto-buffer-fun 'pop-to-buffer)
  (repl-toggle-mode)
```

and the following window layout:

![use_repl_split](https://cloud.githubusercontent.com/assets/70800/20242944/47b39cd4-a939-11e6-9243-386e3073cde4.png)

`C-c C-z` in the REPL switches back to the code, because it calls `rtog/--switch-to-buffer`. However, `C-c C-z` in the elisp file opens `ielm` in the same part of the window:

![repl_toggle2](https://cloud.githubusercontent.com/assets/70800/20242946/7e178aec-a939-11e6-8daa-12c63d650023.png)

**Comment by tomterl** [comment]
This works not as advertised, because `rtog/--switch-to-repl` just calls the repl-start function (`ielm` in this case), and its behaviour kicks in. 

I just pushed a fix, please have a look, try it out and see if it helps you achieve the desired behaviour.

**Comment by tomterl** [comment]
Nota Bene: The call to `(repl-toggle-mode)` in the use-package config Part should be unnecessary

**Comment by tomterl** [comment]
On a side note: Wouldn't it be nice to use `rtog/add-repl` in the config-part of a use-package call of the repl- or language-mode instead of the repl-toggle-mode setup? Like the groovy example? Would you be willing to provide use-package examples for the readme?

**Comment by tomterl** [comment]
Ok - closing it as works-for-me for now ;-); please do re-open this issue if necessary
