### ISSUE TITLE
Only enable repl-toggle on modes in the alist

### ISSUE THREAD

**Issue by matthewbauer** [tomterl/repl-toggle#13]
Currently all prog-mode descendants get enabled. Can this be changed so that it just uses what's configured in rtog/mode-repl-alist?

**Comment by tomterl** [comment]
Probably ;-) -- I'll take a shot at a solution when I have a bit of time free

**Comment by tomterl** [comment]
I should (re)visit my code more often -- the mode should get enabled only if a repl-command was configured for the current major-mode. The following hook is enabled for every `prog-mode` descendant, but `repl-toggle-mode` is only called if a repl-command is set and holds a function:

    (defun rtog/activate ()
      "Activate the repl-toggle minor mode."
      (let ((--mode-cmd  (cdr (assoc major-mode rtog/mode-repl-alist ))))
        (if (and --mode-cmd (functionp --mode-cmd))
             (repl-toggle-mode 1))))

Does this not work for you? I'll check if it does for me and report back here.
