### ISSUE TITLE
Option for fallback function if no repl defined

### ISSUE THREAD

**Issue by orki** [tomterl/repl-toggle#7]
In a mode where there is no REPL defined, could we have an option to provide a fallback function? Something like the following would do it:
```
(defvar rtog/fallback-function nil)
```
and then in `rtog/--switch-to-repl`:
```
(if (functionp rtog/fallback-function)
  (funcall rtog/fallback-function code) ;; even better, add 'ignored'
  (message "--mode-cmd silly? %s" --mode-cmd))
```
where we currently have
```
(message "--mode-cmd silly? %s" --mode-cmd)
```

**Comment by tomterl** [comment]
Do you have an example fallback function?

I'm on vacation with no computer; I'll see to it when I'm back home.

**Comment by orki** [comment]
In c/c++ modes, I use `compile-dwim`; in others, I pipe the region/buffer through an external process.

**Comment by tomterl** [comment]
Apologies for the long delay. Would you be so kind to have a look at the 'fallback-repl' branch? It introduces the `rtog/fallback-repl` customization as per your request and provided solution.
