### ISSUE TITLE
Consider providing default configuration

### ISSUE THREAD

**Issue by Wilfred** [tomterl/repl-toggle#9]
Would you be open to providing a default configuration for common programming languages? I'm happy to submit a PR if you're up for it.

I think this would really help the first impression for new users.

**Comment by tomterl** [comment]
I considered it when I first published the package, but I saw the problem that most of the REPLs configured won't work out-of-the-box, because the packages needed will most likely not be installed...

But I guess a default config really won't hurt -- so I'm open for suggestions

**Comment by tomterl** [comment]
@Wilfred did you lose interest? Or are you just occupied otherwise? In the first case I'd just close the issue, otherwise I'd simply would add `(elisp-mode . ielm)` as default, label the issue as 'backlog' or somesuch and you can add your suggestions as you find the time.

**Comment by tomterl** [comment]
OP has no further interest, I'm fine with the current behaviour -- closing
